//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Codisa.InterwayDocs.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Codisa.InterwayDocs.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed by Codisa IT Solutions &amp; Tiago Freitas Leal.
        /// </summary>
        internal static string AboutFormDeveloperLabel {
            get {
                return ResourceManager.GetString("AboutFormDeveloperLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File: .
        /// </summary>
        internal static string AboutFormFileLabel {
            get {
                return ResourceManager.GetString("AboutFormFileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.en.
        /// </summary>
        internal static string AboutFormHtmlFileName {
            get {
                return ResourceManager.GetString("AboutFormHtmlFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web address: .
        /// </summary>
        internal static string AboutFormUrlLabel {
            get {
                return ResourceManager.GetString("AboutFormUrlLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.codisa-its.com.
        /// </summary>
        internal static string AboutFormUrlLink {
            get {
                return ResourceManager.GetString("AboutFormUrlLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: .
        /// </summary>
        internal static string AboutFormVersionLabel {
            get {
                return ResourceManager.GetString("AboutFormVersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AddNew16 {
            get {
                object obj = ResourceManager.GetObject("AddNew16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal error (AppDomain Unhandled).
        /// </summary>
        internal static string AppDomain_UnhandledException {
            get {
                return ResourceManager.GetString("AppDomain_UnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal error (ThreadException).
        /// </summary>
        internal static string Application_ThreadException {
            get {
                return ResourceManager.GetString("Application_ThreadException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are going to apply the file {0}..
        /// </summary>
        internal static string ApplyingQueryFile {
            get {
                return ResourceManager.GetString("ApplyingQueryFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ArrowDown16 {
            get {
                object obj = ResourceManager.GetObject("ArrowDown16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ArrowUp16 {
            get {
                object obj = ResourceManager.GetObject("ArrowUp16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created on {0}. Changed on {1}.
        /// </summary>
        internal static string AuditChanged {
            get {
                return ResourceManager.GetString("AuditChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd/MM/yyyy a\t HH:mm:ss.
        /// </summary>
        internal static string AuditChangedFormat {
            get {
                return ResourceManager.GetString("AuditChangedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created on {0}. Changed at {1}.
        /// </summary>
        internal static string AuditChangedSameDay {
            get {
                return ResourceManager.GetString("AuditChangedSameDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HH:mm:ss.
        /// </summary>
        internal static string AuditChangedSameDayFormat {
            get {
                return ResourceManager.GetString("AuditChangedSameDayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd/MM/yyyy a\t  HH:mm:ss.
        /// </summary>
        internal static string AuditCreatedFormat {
            get {
                return ResourceManager.GetString("AuditCreatedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created on {0}. No changes..
        /// </summary>
        internal static string AuditNoChanges {
            get {
                return ResourceManager.GetString("AuditNoChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} between {1} and {2}.
        /// </summary>
        internal static string BookReportDateRange {
            get {
                return ResourceManager.GetString("BookReportDateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} since {1}.
        /// </summary>
        internal static string BookReportDateSince {
            get {
                return ResourceManager.GetString("BookReportDateSince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} until {1}.
        /// </summary>
        internal static string BookReportDateUpTo {
            get {
                return ResourceManager.GetString("BookReportDateUpTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}).
        /// </summary>
        internal static string BookReportTitle {
            get {
                return ResourceManager.GetString("BookReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The register isn&apos;t saved. If you close without saving you will loose the changes.
        ///Do you want to close without saving?.
        /// </summary>
        internal static string CloseOrCancel {
            get {
                return ResourceManager.GetString("CloseOrCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report:.
        /// </summary>
        internal static string CommunReportTitle {
            get {
                return ResourceManager.GetString("CommunReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are going to copy the database files..
        /// </summary>
        internal static string CopyDatabaseFiles {
            get {
                return ResourceManager.GetString("CopyDatabaseFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database have been tampered with (the version can&apos;t be empty). Consult your system administrator..
        /// </summary>
        internal static string DatabaseTemperingVersionEmpty {
            get {
                return ResourceManager.GetString("DatabaseTemperingVersionEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database have been tampered with (the version can&apos;t be {0}). Consult your system administrator..
        /// </summary>
        internal static string DatabaseTemperingWrongVersion {
            get {
                return ResourceManager.GetString("DatabaseTemperingWrongVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd/MM/yyyy.
        /// </summary>
        internal static string DateTimeFormat {
            get {
                return ResourceManager.GetString("DateTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Delete16 {
            get {
                object obj = ResourceManager.GetObject("Delete16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery mail book.
        /// </summary>
        internal static string DeliveryBookDisplayName {
            get {
                return ResourceManager.GetString("DeliveryBookDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery.
        /// </summary>
        internal static string DeliveryBookShortName {
            get {
                return ResourceManager.GetString("DeliveryBookShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery mail register.
        /// </summary>
        internal static string DeliveryRegisterReportName {
            get {
                return ResourceManager.GetString("DeliveryRegisterReportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Edit16 {
            get {
                object obj = ResourceManager.GetObject("Edit16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email@support.sup.
        /// </summary>
        internal static string EmailSupport {
            get {
                return ResourceManager.GetString("EmailSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EmailView {
            get {
                object obj = ResourceManager.GetObject("EmailView", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Excel {
            get {
                object obj = ResourceManager.GetObject("Excel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Workbook(*.xlsx)|*.xlsx.
        /// </summary>
        internal static string ExcelWorkbook {
            get {
                return ResourceManager.GetString("ExcelWorkbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select search mode..
        /// </summary>
        internal static string FastDateToolTip {
            get {
                return ResourceManager.GetString("FastDateToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal error.
        /// </summary>
        internal static string FatalError {
            get {
                return ResourceManager.GetString("FatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy-MM-dd HHmmss.
        /// </summary>
        internal static string FilenameDateTimeFormat {
            get {
                return ResourceManager.GetString("FilenameDateTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide search panel.
        /// </summary>
        internal static string HideSearchPanel {
            get {
                return ResourceManager.GetString("HideSearchPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incoming mail book.
        /// </summary>
        internal static string IncomingBookDisplayName {
            get {
                return ResourceManager.GetString("IncomingBookDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incoming.
        /// </summary>
        internal static string IncomingBookShortName {
            get {
                return ResourceManager.GetString("IncomingBookShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incoming mail register.
        /// </summary>
        internal static string IncomingRegisterReportName {
            get {
                return ResourceManager.GetString("IncomingRegisterReportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incoming register.
        /// </summary>
        internal static string IncomingRegisterShortName {
            get {
                return ResourceManager.GetString("IncomingRegisterShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About InterwayDocs.
        /// </summary>
        internal static string LabelAboutApplication {
            get {
                return ResourceManager.GetString("LabelAboutApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        internal static string LabelAlert {
            get {
                return ResourceManager.GetString("LabelAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string LabelArchiveLocation {
            get {
                return ResourceManager.GetString("LabelArchiveLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to create a delivery mail register.
        /// </summary>
        internal static string LabelClickCreateDelivery {
            get {
                return ResourceManager.GetString("LabelClickCreateDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to create an incoming mail register.
        /// </summary>
        internal static string LabelClickCreateIncoming {
            get {
                return ResourceManager.GetString("LabelClickCreateIncoming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to create an outgoing mail register.
        /// </summary>
        internal static string LabelClickCreateOutgoing {
            get {
                return ResourceManager.GetString("LabelClickCreateOutgoing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dates.
        /// </summary>
        internal static string LabelDates {
            get {
                return ResourceManager.GetString("LabelDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery.
        /// </summary>
        internal static string LabelDelivery {
            get {
                return ResourceManager.GetString("LabelDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        internal static string LabelDocument {
            get {
                return ResourceManager.GetString("LabelDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Manual (PDF).
        /// </summary>
        internal static string LabelDocumentation {
            get {
                return ResourceManager.GetString("LabelDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Until.
        /// </summary>
        internal static string LabelEndDate {
            get {
                return ResourceManager.GetString("LabelEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free text.
        /// </summary>
        internal static string LabelFullText {
            get {
                return ResourceManager.GetString("LabelFullText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string LabelHelp {
            get {
                return ResourceManager.GetString("LabelHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incoming.
        /// </summary>
        internal static string LabelIncoming {
            get {
                return ResourceManager.GetString("LabelIncoming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outgoing.
        /// </summary>
        internal static string LabelOutgoing {
            get {
                return ResourceManager.GetString("LabelOutgoing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string LabelSearch {
            get {
                return ResourceManager.GetString("LabelSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since.
        /// </summary>
        internal static string LabelStartDate {
            get {
                return ResourceManager.GetString("LabelStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string LabelTools {
            get {
                return ResourceManager.GetString("LabelTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InterwayDocs - Mail registry.
        /// </summary>
        internal static string MainFormTitle {
            get {
                return ResourceManager.GetString("MainFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database file {0} wasn&apos;t found..
        /// </summary>
        internal static string MissingDatabaseFile {
            get {
                return ResourceManager.GetString("MissingDatabaseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MoveBack16 {
            get {
                object obj = ResourceManager.GetObject("MoveBack16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MoveFirst16 {
            get {
                object obj = ResourceManager.GetObject("MoveFirst16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MoveLast16 {
            get {
                object obj = ResourceManager.GetObject("MoveLast16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MoveNext16 {
            get {
                object obj = ResourceManager.GetObject("MoveNext16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New register.
        /// </summary>
        internal static string NewRegister {
            get {
                return ResourceManager.GetString("NewRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No registers to show.
        /// </summary>
        internal static string NoAvailableRegisters {
            get {
                return ResourceManager.GetString("NoAvailableRegisters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database or files have been tampered with (there is no update script for version {0}). Consult your system administrator..
        /// </summary>
        internal static string NoScriptForVersion {
            get {
                return ResourceManager.GetString("NoScriptForVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation error.
        /// </summary>
        internal static string OperationError {
            get {
                return ResourceManager.GetString("OperationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outgoing mail book.
        /// </summary>
        internal static string OutgoingBookDisplayName {
            get {
                return ResourceManager.GetString("OutgoingBookDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outgoing.
        /// </summary>
        internal static string OutgoingBookShortName {
            get {
                return ResourceManager.GetString("OutgoingBookShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outgoing mail register.
        /// </summary>
        internal static string OutgoingRegisterReportName {
            get {
                return ResourceManager.GetString("OutgoingRegisterReportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outgoing register.
        /// </summary>
        internal static string OutgoingRegisterShortName {
            get {
                return ResourceManager.GetString("OutgoingRegisterShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recreate the objects in the database..
        /// </summary>
        internal static string RefreshigDbObjects {
            get {
                return ResourceManager.GetString("RefreshigDbObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register nr. {0}.
        /// </summary>
        internal static string RegisterNumber {
            get {
                return ResourceManager.GetString("RegisterNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} with {1} {2} ({3}).
        /// </summary>
        internal static string RegisterReportTitle {
            get {
                return ResourceManager.GetString("RegisterReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historic:.
        /// </summary>
        internal static string ReportLabelAudit {
            get {
                return ResourceManager.GetString("ReportLabelAudit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Save16 {
            get {
                object obj = ResourceManager.GetObject("Save16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save error.
        /// </summary>
        internal static string SaveError {
            get {
                return ResourceManager.GetString("SaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SplashImage {
            get {
                object obj = ResourceManager.GetObject("SplashImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make a data backup.
        /// </summary>
        internal static string ToolsBackupLabel {
            get {
                return ResourceManager.GetString("ToolsBackupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export data.
        /// </summary>
        internal static string ToolsExportlabel {
            get {
                return ResourceManager.GetString("ToolsExportlabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import data.
        /// </summary>
        internal static string ToolsImportLabel {
            get {
                return ResourceManager.GetString("ToolsImportLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore data backup.
        /// </summary>
        internal static string ToolsRestoreLabel {
            get {
                return ResourceManager.GetString("ToolsRestoreLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel changes.
        /// </summary>
        internal static string ToolTipCancel {
            get {
                return ResourceManager.GetString("ToolTipCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page nr. / Page total.
        /// </summary>
        internal static string ToolTipCurrentPageTotalPages {
            get {
                return ResourceManager.GetString("ToolTipCurrentPageTotalPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the date type you want to search for..
        /// </summary>
        internal static string ToolTipDates {
            get {
                return ResourceManager.GetString("ToolTipDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document classification code.
        /// </summary>
        internal static string ToolTipDocumentClass {
            get {
                return ResourceManager.GetString("ToolTipDocumentClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date that is written on the document..
        /// </summary>
        internal static string ToolTipDocumentDate {
            get {
                return ResourceManager.GetString("ToolTipDocumentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department that produced the document..
        /// </summary>
        internal static string ToolTipDocumentDept {
            get {
                return ResourceManager.GetString("ToolTipDocumentDept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Producing Entity.
        /// </summary>
        internal static string ToolTipDocumentEntity {
            get {
                return ResourceManager.GetString("ToolTipDocumentEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number that is written on the document..
        /// </summary>
        internal static string ToolTipDocumentNumber {
            get {
                return ResourceManager.GetString("ToolTipDocumentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document type.
        /// </summary>
        internal static string ToolTipDocumentType {
            get {
                return ResourceManager.GetString("ToolTipDocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit the register..
        /// </summary>
        internal static string ToolTipEdit {
            get {
                return ResourceManager.GetString("ToolTipEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search until this date (inclusive). 
        ///If empty, finds the newest documents..
        /// </summary>
        internal static string ToolTipEndDate {
            get {
                return ResourceManager.GetString("ToolTipEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person that sent the document.
        /// </summary>
        internal static string ToolTipExpeditorName {
            get {
                return ResourceManager.GetString("ToolTipExpeditorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export the list to Excel.
        /// </summary>
        internal static string ToolTipExportListExcel {
            get {
                return ResourceManager.GetString("ToolTipExportListExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export the register to Excel.
        /// </summary>
        internal static string ToolTipExportRegisterExcel {
            get {
                return ResourceManager.GetString("ToolTipExportRegisterExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First page.
        /// </summary>
        internal static string ToolTipFirstPage {
            get {
                return ResourceManager.GetString("ToolTipFirstPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type the words that will be searched in all fields, 
        ///up to three words..
        /// </summary>
        internal static string ToolTipFullText {
            get {
                return ResourceManager.GetString("ToolTipFullText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide the register.
        /// </summary>
        internal static string ToolTipHideDetail {
            get {
                return ResourceManager.GetString("ToolTipHideDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last page.
        /// </summary>
        internal static string ToolTipLastPage {
            get {
                return ResourceManager.GetString("ToolTipLastPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location where the document is archived..
        /// </summary>
        internal static string ToolTipLocation {
            get {
                return ResourceManager.GetString("ToolTipLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New register.
        /// </summary>
        internal static string ToolTipNew {
            get {
                return ResourceManager.GetString("ToolTipNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next page.
        /// </summary>
        internal static string ToolTipNextPage {
            get {
                return ResourceManager.GetString("ToolTipNextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous page.
        /// </summary>
        internal static string ToolTipPreviousPage {
            get {
                return ResourceManager.GetString("ToolTipPreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document reception date..
        /// </summary>
        internal static string ToolTipReceptionDate {
            get {
                return ResourceManager.GetString("ToolTipReceptionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person who received the document.
        /// </summary>
        internal static string ToolTipReceptionName {
            get {
                return ResourceManager.GetString("ToolTipReceptionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document recipient.
        /// </summary>
        internal static string ToolTipRecipientName {
            get {
                return ResourceManager.GetString("ToolTipRecipientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document recipient town.
        /// </summary>
        internal static string ToolTipRecipientTown {
            get {
                return ResourceManager.GetString("ToolTipRecipientTown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document creation date..
        /// </summary>
        internal static string ToolTipRegisterDate {
            get {
                return ResourceManager.GetString("ToolTipRegisterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person or department for whom the document was forwarded..
        /// </summary>
        internal static string ToolTipRoutedTo {
            get {
                return ResourceManager.GetString("ToolTipRoutedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm changes.
        /// </summary>
        internal static string ToolTipSave {
            get {
                return ResourceManager.GetString("ToolTipSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of document dispatch.
        /// </summary>
        internal static string ToolTipSendDate {
            get {
                return ResourceManager.GetString("ToolTipSendDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin of the document.
        /// </summary>
        internal static string ToolTipSenderName {
            get {
                return ResourceManager.GetString("ToolTipSenderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the register.
        /// </summary>
        internal static string ToolTipShowDetailPanel {
            get {
                return ResourceManager.GetString("ToolTipShowDetailPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the search panel.
        /// </summary>
        internal static string ToolTipShowSearchPanel {
            get {
                return ResourceManager.GetString("ToolTipShowSearchPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search since this date (inclusive). 
        ///If empty, finds the oldest documents..
        /// </summary>
        internal static string ToolTipStartDate {
            get {
                return ResourceManager.GetString("ToolTipStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document subject.
        /// </summary>
        internal static string ToolTipSubject {
            get {
                return ResourceManager.GetString("ToolTipSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved register.
        /// </summary>
        internal static string UnsavedRegister {
            get {
                return ResourceManager.GetString("UnsavedRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;not filled&gt;.
        /// </summary>
        internal static string Unspecified {
            get {
                return ResourceManager.GetString("Unspecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are going to upgrade version {0} to {1}..
        /// </summary>
        internal static string UpgradingVersion {
            get {
                return ResourceManager.GetString("UpgradingVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Validate16 {
            get {
                object obj = ResourceManager.GetObject("Validate16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
